# This workflow migrates large files to git lfs

name: Migrate large files to GIT LFS

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - uses: actions/checkout@v3
      with: 
        fetch-depth: '0'
    - name: Configure Git LFS
      run: |
        git lfs migrate import --everything --include="*.m4a" --verbose
# git lfs track "*.m4a"
# git add .gitattributes
# git commit -m "Setup LFS"
    - name: Force push
      run: |
        git push --force --all
        
